/*******************************************************************************
 * Copyright (c) 2006, 2007 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.cdt.core.dom.c99;

import org.eclipse.cdt.core.dom.parser.c99.IToken;
import org.eclipse.cdt.core.dom.parser.c99.PPToken;

/**
 * Interface that specifies preprocessor tokens and comparator objects
 * that the preprocessor will use to interpret regular tokens
 * as preprocessor tokens.
 * 
 * @author Mike Kucera
 */
public interface IPPTokenComparator {
	
	
	/**
	 * Kind codes for tokens that are generated by the preprocessor.
	 * 
	 * The preprocessor needs to generate certain types of tokens
	 * (for example when using the ## operator), these token kinds
	 * that can be generated are listed here.
	 */
	public static final int 
		KIND_IDENTIFIER = 0,
		KIND_EOF = 1,
		KIND_COMPLETION = 2,
		KIND_END_OF_COMPLETION = 3,
		KIND_INTEGER = 4,
		KIND_STRINGLIT = 5,
		KIND_INVALID = 6;
		
	
	/**
	 * Returns true if the given IToken should be interpreted
	 * as the given PPToken.
	 */
	public boolean compare(PPToken pptoken, IToken token);
	
	
	/**
	 * Returns the specific parser token kind that corresponds
	 * to the given kind code. The kind codes are listed as static
	 * fields of this class.
	 */
	public int getKind(int tokenToMake);
	
	
	
	/**
	 * Returns the orderedTerminalSymbols field from an LPG based parser.
	 * Used by C99ExprEvaluator to make sense of tokens from any LPG parser.
	 */
	public String[] getLPGOrderedTerminalSymbols();
}
