/*******************************************************************************
* Copyright (c) 2006, 2007 IBM Corporation and others.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*     IBM Corporation - initial API and implementation
*******************************************************************************/

// This file was generated by LPG

package org.eclipse.cdt.internal.core.dom.parser.c99;

public interface C99ExprEvaluatorsym {
    public final static int
      TK_RightParen = 18,
      TK_LeftParen = 19,
      TK_And = 12,
      TK_Star = 5,
      TK_Plus = 3,
      TK_Minus = 4,
      TK_Tilde = 20,
      TK_Bang = 21,
      TK_Slash = 6,
      TK_Percent = 7,
      TK_RightShift = 1,
      TK_LeftShift = 2,
      TK_LT = 8,
      TK_GT = 9,
      TK_LE = 10,
      TK_GE = 11,
      TK_EQ = 13,
      TK_NE = 14,
      TK_Caret = 15,
      TK_Or = 16,
      TK_AndAnd = 17,
      TK_OrOr = 22,
      TK_Question = 23,
      TK_Colon = 24,
      TK_integer = 25,
      TK_charconst = 26,
      TK_identifier = 27,
      TK_EOF_TOKEN = 28,
      TK_ERROR_TOKEN = 29;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "RightShift",
                 "LeftShift",
                 "Plus",
                 "Minus",
                 "Star",
                 "Slash",
                 "Percent",
                 "LT",
                 "GT",
                 "LE",
                 "GE",
                 "And",
                 "EQ",
                 "NE",
                 "Caret",
                 "Or",
                 "AndAnd",
                 "RightParen",
                 "LeftParen",
                 "Tilde",
                 "Bang",
                 "OrOr",
                 "Question",
                 "Colon",
                 "integer",
                 "charconst",
                 "identifier",
                 "EOF_TOKEN",
                 "ERROR_TOKEN"
             };

    public final static boolean isValidForParser = true;
}
