/*******************************************************************************
 * Copyright (c) 2006, 2007 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package org.eclipse.cdt.internal.core.dom.parser.c99;

public interface C99LexerBaseexp {
    public final static int
      TK_EOF_TOKEN = 1,
      TK_auto = 2,
      TK_break = 3,
      TK_case = 4,
      TK_char = 5,
      TK_const = 6,
      TK_continue = 7,
      TK_default = 8,
      TK_do = 9,
      TK_double = 10,
      TK_else = 11,
      TK_enum = 12,
      TK_extern = 13,
      TK_float = 14,
      TK_for = 15,
      TK_goto = 16,
      TK_if = 17,
      TK_inline = 18,
      TK_int = 19,
      TK_long = 20,
      TK_register = 21,
      TK_restrict = 22,
      TK_return = 23,
      TK_short = 24,
      TK_signed = 25,
      TK_sizeof = 26,
      TK_static = 27,
      TK_struct = 28,
      TK_switch = 29,
      TK_typedef = 30,
      TK_union = 31,
      TK_unsigned = 32,
      TK_void = 33,
      TK_volatile = 34,
      TK_while = 35,
      TK__Bool = 36,
      TK__Complex = 37,
      TK__Imaginary = 38,
      TK_identifier = 39,
      TK_integer = 40,
      TK_floating = 41,
      TK_charconst = 42,
      TK_stringlit = 43,
      TK_RightBracket = 44,
      TK_LeftBracket = 45,
      TK_RightParen = 46,
      TK_LeftParen = 47,
      TK_RightBrace = 48,
      TK_LeftBrace = 49,
      TK_Dot = 50,
      TK_Arrow = 51,
      TK_PlusPlus = 52,
      TK_MinusMinus = 53,
      TK_And = 54,
      TK_Star = 55,
      TK_Plus = 56,
      TK_Minus = 57,
      TK_Tilde = 58,
      TK_Bang = 59,
      TK_Slash = 60,
      TK_Percent = 61,
      TK_RightShift = 62,
      TK_LeftShift = 63,
      TK_LT = 64,
      TK_GT = 65,
      TK_LE = 66,
      TK_GE = 67,
      TK_EQ = 68,
      TK_NE = 69,
      TK_Caret = 70,
      TK_Or = 71,
      TK_AndAnd = 72,
      TK_OrOr = 73,
      TK_Question = 74,
      TK_Colon = 75,
      TK_SemiColon = 76,
      TK_DotDotDot = 77,
      TK_Assign = 78,
      TK_StarAssign = 79,
      TK_SlashAssign = 80,
      TK_PercentAssign = 81,
      TK_PlusAssign = 82,
      TK_MinusAssign = 83,
      TK_RightShiftAssign = 84,
      TK_LeftShiftAssign = 85,
      TK_AndAssign = 86,
      TK_CaretAssign = 87,
      TK_OrAssign = 88,
      TK_Comma = 89,
      TK_Hash = 90,
      TK_HashHash = 91;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "EOF_TOKEN",
                 "auto",
                 "break",
                 "case",
                 "char",
                 "const",
                 "continue",
                 "default",
                 "do",
                 "double",
                 "else",
                 "enum",
                 "extern",
                 "float",
                 "for",
                 "goto",
                 "if",
                 "inline",
                 "int",
                 "long",
                 "register",
                 "restrict",
                 "return",
                 "short",
                 "signed",
                 "sizeof",
                 "static",
                 "struct",
                 "switch",
                 "typedef",
                 "union",
                 "unsigned",
                 "void",
                 "volatile",
                 "while",
                 "_Bool",
                 "_Complex",
                 "_Imaginary",
                 "identifier",
                 "integer",
                 "floating",
                 "charconst",
                 "stringlit",
                 "RightBracket",
                 "LeftBracket",
                 "RightParen",
                 "LeftParen",
                 "RightBrace",
                 "LeftBrace",
                 "Dot",
                 "Arrow",
                 "PlusPlus",
                 "MinusMinus",
                 "And",
                 "Star",
                 "Plus",
                 "Minus",
                 "Tilde",
                 "Bang",
                 "Slash",
                 "Percent",
                 "RightShift",
                 "LeftShift",
                 "LT",
                 "GT",
                 "LE",
                 "GE",
                 "EQ",
                 "NE",
                 "Caret",
                 "Or",
                 "AndAnd",
                 "OrOr",
                 "Question",
                 "Colon",
                 "SemiColon",
                 "DotDotDot",
                 "Assign",
                 "StarAssign",
                 "SlashAssign",
                 "PercentAssign",
                 "PlusAssign",
                 "MinusAssign",
                 "RightShiftAssign",
                 "LeftShiftAssign",
                 "AndAssign",
                 "CaretAssign",
                 "OrAssign",
                 "Comma",
                 "Hash",
                 "HashHash"
             };


    public final static boolean isValidForParser = false;
}
