/*******************************************************************************
* Copyright (c) 2006, 2007 IBM Corporation and others.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*     IBM Corporation - initial API and implementation
*******************************************************************************/

// This file was generated by LPG

package org.eclipse.cdt.internal.core.dom.parser.c99;

import lpg.lpgjavaruntime.*;

import java.util.*;

import org.eclipse.cdt.core.dom.ast.*;
import org.eclipse.cdt.internal.core.dom.parser.c.*;
import org.eclipse.cdt.core.dom.ast.c.*;
import org.eclipse.cdt.core.dom.c99.IPreprocessorTokenOuput;
import org.eclipse.cdt.internal.core.parser.scanner2.ILocationResolver;
import org.eclipse.cdt.core.index.IIndex;

public class C99Parser extends PrsStream implements RuleAction , IPreprocessorTokenOuput 
{
    private static ParseTable prs = new C99Parserprs();
    private BacktrackingParser btParser;

    public BacktrackingParser getParser() { return btParser; }
    private void setResult(Object object) { btParser.setSym1(object); }
    public Object getRhsSym(int i) { return btParser.getSym(i); }

    public int getRhsTokenIndex(int i) { return btParser.getToken(i); }
    public IToken getRhsIToken(int i) { return super.getIToken(getRhsTokenIndex(i)); }
    
    public int getRhsFirstTokenIndex(int i) { return btParser.getFirstToken(i); }
    public IToken getRhsFirstIToken(int i) { return super.getIToken(getRhsFirstTokenIndex(i)); }

    public int getRhsLastTokenIndex(int i) { return btParser.getLastToken(i); }
    public IToken getRhsLastIToken(int i) { return super.getIToken(getRhsLastTokenIndex(i)); }

    public int getLeftSpan() { return btParser.getFirstToken(); }
    public IToken getLeftIToken()  { return super.getIToken(getLeftSpan()); }

    public int getRightSpan() { return btParser.getLastToken(); }
    public IToken getRightIToken() { return super.getIToken(getRightSpan()); }

    public int getRhsErrorTokenIndex(int i)
    {
        int index = btParser.getToken(i);
        IToken err = super.getIToken(index);
        return (err instanceof ErrorToken ? index : 0);
    }
    public ErrorToken getRhsErrorIToken(int i)
    {
        int index = btParser.getToken(i);
        IToken err = super.getIToken(index);
        return (ErrorToken) (err instanceof ErrorToken ? err : null);
    }

    public C99Parser(LexStream lexStream)
    {
        super(lexStream);

        try
        {
            super.remapTerminalSymbols(orderedTerminalSymbols(), C99Parserprs.EOFT_SYMBOL);
        }
        catch(NullExportedSymbolsException e) {
        }
        catch(NullTerminalSymbolsException e) {
        }
        catch(UnimplementedTerminalsException e)
        {
            java.util.ArrayList unimplemented_symbols = e.getSymbols();
            System.out.println("The Lexer will not scan the following token(s):");
            for (int i = 0; i < unimplemented_symbols.size(); i++)
            {
                Integer id = (Integer) unimplemented_symbols.get(i);
                System.out.println("    " + C99Parsersym.orderedTerminalSymbols[id.intValue()]);               
            }
            System.out.println();                        
        }
        catch(UndefinedEofSymbolException e)
        {
            throw new Error(new UndefinedEofSymbolException
                                ("The Lexer does not implement the Eof symbol " +
                                 C99Parsersym.orderedTerminalSymbols[C99Parserprs.EOFT_SYMBOL]));
        } 
    }

    public String[] orderedTerminalSymbols() { return C99Parsersym.orderedTerminalSymbols; }
    public String getTokenKindName(int kind) { return C99Parsersym.orderedTerminalSymbols[kind]; }
    public int getEOFTokenKind() { return C99Parserprs.EOFT_SYMBOL; }
    public PrsStream getParseStream() { return (PrsStream) this; }
    
    //
    // Report error message for given error_token.
    //
    public final void reportErrorTokenMessage(int error_token, String msg)
    {
        int firsttok = super.getFirstErrorToken(error_token),
            lasttok = super.getLastErrorToken(error_token);
        String location = super.getFileName() + ':' +
                          (firsttok > lasttok
                                    ? (super.getEndLine(lasttok) + ":" + super.getEndColumn(lasttok))
                                    : (super.getLine(error_token) + ":" +
                                       super.getColumn(error_token) + ":" +
                                       super.getEndLine(error_token) + ":" +
                                       super.getEndColumn(error_token)))
                          + ": ";
        super.reportError((firsttok > lasttok ? ParseErrorCodes.INSERTION_CODE : ParseErrorCodes.SUBSTITUTION_CODE), location, msg);
    }

    public Object parser()
    {
        return parser(null, 0);
    }
    
    public Object parser(Monitor monitor)
    {
        return parser(monitor, 0);
    }
    
    public Object parser(int error_repair_count)
    {
        return parser(null, error_repair_count);
    }

    public Object parser(Monitor monitor, int error_repair_count)
    {
        try
        {
            btParser = new BacktrackingParser(monitor, (TokenStream) this, prs, (RuleAction) this);
        }
        catch (NotBacktrackParseTableException e)
        {
            throw new Error(new NotBacktrackParseTableException
                                ("Regenerate C99Parserprs.java with -BACKTRACK option"));
        }
        catch (BadParseSymFileException e)
        {
            throw new Error(new BadParseSymFileException("Bad Parser Symbol File -- C99Parsersym.java"));
        }

        try
        {
            return (Object) btParser.parse(error_repair_count);
        }
        catch (BadParseException e)
        {
            reset(e.error_token); // point to error token
            DiagnoseParser diagnoseParser = new DiagnoseParser(this, prs);
            diagnoseParser.diagnose(e.error_token);
        }

        return null;
    }


private C99ParserAction action = new C99ParserAction(this);

public C99Parser() {}

public IASTTranslationUnit parse(ILocationResolver resolver, IIndex index) {
	action.setResolver(resolver);
	action.setIndex(index);
	parser(null, -1);
	return action.getAST();
}

public void prepareToParse() {
	// this has to be done, or... kaboom!
	setStreamLength(getSize());
}

public boolean encounteredError() {
	return action.encounteredError();
}

    public void ruleAction(int ruleNumber)
    {
        switch (ruleNumber)
        {
 
            //
            // Rule 1:  <openscope> ::= $Empty
            //
            case 1: { action.beforeConsume(); action.   openASTScope();            break;
            }
 
            //
            // Rule 2:  constant ::= integer
            //
            case 2: { action.beforeConsume(); action.   consumeExpressionConstant(IASTLiteralExpression.lk_integer_constant);            break;
            }
 
            //
            // Rule 3:  constant ::= floating
            //
            case 3: { action.beforeConsume(); action.   consumeExpressionConstant(IASTLiteralExpression.lk_float_constant);              break;
            }
 
            //
            // Rule 4:  constant ::= charconst
            //
            case 4: { action.beforeConsume(); action.   consumeExpressionConstant(IASTLiteralExpression.lk_char_constant);               break;
            }
 
            //
            // Rule 5:  constant ::= stringlit
            //
            case 5: { action.beforeConsume(); action.   consumeExpressionConstant(IASTLiteralExpression.lk_string_literal);              break;
            }
 
            //
            // Rule 7:  primary_expression ::= identifier
            //
            case 7: { action.beforeConsume(); action.   consumeExpressionID();            break;
            }
 
            //
            // Rule 8:  primary_expression ::= ( expression )
            //
            case 8: { action.beforeConsume(); action.   consumeExpressionBracketed();            break;
            }
 
            //
            // Rule 10:  postfix_expression ::= postfix_expression [ expression ]
            //
            case 10: { action.beforeConsume(); action.   consumeExpressionArraySubscript();            break;
            }
 
            //
            // Rule 11:  postfix_expression ::= postfix_expression ( )
            //
            case 11: { action.beforeConsume(); action.   consumeExpressionFunctionCall(false);            break;
            }
 
            //
            // Rule 12:  postfix_expression ::= postfix_expression ( argument_expression_list )
            //
            case 12: { action.beforeConsume(); action.   consumeExpressionFunctionCall(true);            break;
            }
 
            //
            // Rule 13:  postfix_expression ::= postfix_expression . identifier
            //
            case 13: { action.beforeConsume(); action.   consumeExpressionFieldReference(false);            break;
            }
 
            //
            // Rule 14:  postfix_expression ::= postfix_expression -> identifier
            //
            case 14: { action.beforeConsume(); action.   consumeExpressionFieldReference(true);            break;
            }
 
            //
            // Rule 15:  postfix_expression ::= postfix_expression ++
            //
            case 15: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_postFixIncr);            break;
            }
 
            //
            // Rule 16:  postfix_expression ::= postfix_expression --
            //
            case 16: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_postFixDecr);            break;
            }
 
            //
            // Rule 17:  postfix_expression ::= ( type_name ) { <openscope> initializer_list }
            //
            case 17: { action.beforeConsume(); action.   consumeExpressionTypeIdInitializer();            break;
            }
 
            //
            // Rule 18:  postfix_expression ::= ( type_name ) { <openscope> initializer_list , }
            //
            case 18: { action.beforeConsume(); action.   consumeExpressionTypeIdInitializer();            break;
            }
 
            //
            // Rule 19:  argument_expression_list ::= assignment_expression
            //
            case 19: { action.beforeConsume(); action.   consumeExpressionArgumentExpressionList(true);            break;
            }
 
            //
            // Rule 20:  argument_expression_list ::= argument_expression_list , assignment_expression
            //
            case 20: { action.beforeConsume(); action.   consumeExpressionArgumentExpressionList(false);           break;
            }
 
            //
            // Rule 22:  unary_expression ::= ++ unary_expression
            //
            case 22: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_prefixIncr);            break;
            }
 
            //
            // Rule 23:  unary_expression ::= -- unary_expression
            //
            case 23: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_prefixDecr);            break;
            }
 
            //
            // Rule 24:  unary_expression ::= & cast_expression
            //
            case 24: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_amper);            break;
            }
 
            //
            // Rule 25:  unary_expression ::= * cast_expression
            //
            case 25: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_star);             break;
            }
 
            //
            // Rule 26:  unary_expression ::= + cast_expression
            //
            case 26: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_plus);             break;
            }
 
            //
            // Rule 27:  unary_expression ::= - cast_expression
            //
            case 27: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_minus);            break;
            }
 
            //
            // Rule 28:  unary_expression ::= ~ cast_expression
            //
            case 28: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_tilde);            break;
            }
 
            //
            // Rule 29:  unary_expression ::= ! cast_expression
            //
            case 29: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_not);              break;
            }
 
            //
            // Rule 30:  unary_expression ::= sizeof unary_expression
            //
            case 30: { action.beforeConsume(); action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_sizeof);           break;
            }
 
            //
            // Rule 31:  unary_expression ::= sizeof ( type_name )
            //
            case 31: { action.beforeConsume(); action.   consumeExpressionUnarySizeofTypeName();            break;
            }
 
            //
            // Rule 33:  cast_expression ::= ( type_name ) cast_expression
            //
            case 33: { action.beforeConsume(); action.   consumeExpressionCast();            break;
            }
 
            //
            // Rule 35:  multiplicative_expression ::= multiplicative_expression * cast_expression
            //
            case 35: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_multiply);           break;
            }
 
            //
            // Rule 36:  multiplicative_expression ::= multiplicative_expression / cast_expression
            //
            case 36: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_divide);             break;
            }
 
            //
            // Rule 37:  multiplicative_expression ::= multiplicative_expression % cast_expression
            //
            case 37: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_modulo);             break;
            }
 
            //
            // Rule 39:  additive_expression ::= additive_expression + multiplicative_expression
            //
            case 39: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_plus);            break;
            }
 
            //
            // Rule 40:  additive_expression ::= additive_expression - multiplicative_expression
            //
            case 40: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_minus);           break;
            }
 
            //
            // Rule 42:  shift_expression ::= shift_expression << additive_expression
            //
            case 42: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_shiftLeft);             break;
            }
 
            //
            // Rule 43:  shift_expression ::= shift_expression >> additive_expression
            //
            case 43: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_shiftRight);            break;
            }
 
            //
            // Rule 45:  relational_expression ::= relational_expression < shift_expression
            //
            case 45: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_lessThan);               break;
            }
 
            //
            // Rule 46:  relational_expression ::= relational_expression > shift_expression
            //
            case 46: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_greaterThan);            break;
            }
 
            //
            // Rule 47:  relational_expression ::= relational_expression <= shift_expression
            //
            case 47: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_lessEqual);              break;
            }
 
            //
            // Rule 48:  relational_expression ::= relational_expression >= shift_expression
            //
            case 48: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_greaterEqual);           break;
            }
 
            //
            // Rule 50:  equality_expression ::= equality_expression == relational_expression
            //
            case 50: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_equals);            break;
            }
 
            //
            // Rule 51:  equality_expression ::= equality_expression != relational_expression
            //
            case 51: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_notequals);            break;
            }
 
            //
            // Rule 53:  AND_expression ::= AND_expression & equality_expression
            //
            case 53: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_binaryAnd);            break;
            }
 
            //
            // Rule 55:  exclusive_OR_expression ::= exclusive_OR_expression ^ AND_expression
            //
            case 55: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_binaryXor);            break;
            }
 
            //
            // Rule 57:  inclusive_OR_expression ::= inclusive_OR_expression | exclusive_OR_expression
            //
            case 57: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_binaryOr);            break;
            }
 
            //
            // Rule 59:  logical_AND_expression ::= logical_AND_expression && inclusive_OR_expression
            //
            case 59: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_logicalAnd);            break;
            }
 
            //
            // Rule 61:  logical_OR_expression ::= logical_OR_expression || logical_AND_expression
            //
            case 61: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_logicalOr);            break;
            }
 
            //
            // Rule 63:  conditional_expression ::= logical_OR_expression ? expression : conditional_expression
            //
            case 63: { action.beforeConsume(); action.   consumeExpressionConditional();            break;
            }
 
            //
            // Rule 65:  assignment_expression ::= unary_expression = assignment_expression
            //
            case 65: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_assign);            break;
            }
 
            //
            // Rule 66:  assignment_expression ::= unary_expression *= assignment_expression
            //
            case 66: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_multiplyAssign);            break;
            }
 
            //
            // Rule 67:  assignment_expression ::= unary_expression /= assignment_expression
            //
            case 67: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_divideAssign);            break;
            }
 
            //
            // Rule 68:  assignment_expression ::= unary_expression %= assignment_expression
            //
            case 68: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_moduloAssign);            break;
            }
 
            //
            // Rule 69:  assignment_expression ::= unary_expression += assignment_expression
            //
            case 69: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_plusAssign);            break;
            }
 
            //
            // Rule 70:  assignment_expression ::= unary_expression -= assignment_expression
            //
            case 70: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_minusAssign);            break;
            }
 
            //
            // Rule 71:  assignment_expression ::= unary_expression <<= assignment_expression
            //
            case 71: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_shiftLeftAssign);            break;
            }
 
            //
            // Rule 72:  assignment_expression ::= unary_expression >>= assignment_expression
            //
            case 72: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_shiftRightAssign);            break;
            }
 
            //
            // Rule 73:  assignment_expression ::= unary_expression &= assignment_expression
            //
            case 73: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_binaryAndAssign);            break;
            }
 
            //
            // Rule 74:  assignment_expression ::= unary_expression ^= assignment_expression
            //
            case 74: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_binaryXorAssign);            break;
            }
 
            //
            // Rule 75:  assignment_expression ::= unary_expression |= assignment_expression
            //
            case 75: { action.beforeConsume(); action.   consumeExpressionBinaryOperator(IASTBinaryExpression.op_binaryOrAssign);            break;
            }
 
            //
            // Rule 76:  expression_in_statement ::= expression_list
            //
            case 76: { action.beforeConsume(); action.   consumeExpression();            break;
            }
 
            //
            // Rule 77:  expression ::= expression_list
            //
            case 77: { action.beforeConsume(); action.   consumeExpression();            break;
            }
 
            //
            // Rule 78:  expression_list ::= assignment_expression
            //
            case 78: { action.beforeConsume(); action.   consumeExpressionList(true);            break;
            }
 
            //
            // Rule 79:  expression_list ::= expression_list , assignment_expression
            //
            case 79: { action.beforeConsume(); action.   consumeExpressionList(false);            break;
            }
 
            //
            // Rule 83:  statement ::= ERROR_TOKEN
            //
            case 83: { action.beforeConsume(); action.   consumeStatementProblem();            break;
            }
 
            //
            // Rule 84:  labeled_statement ::= label_identifier : unmatched_statement
            //
            case 84: { action.beforeConsume(); action.   consumeStatementLabeled();            break;
            }
 
            //
            // Rule 85:  labeled_statement ::= case constant_expression : unmatched_statement
            //
            case 85: { action.beforeConsume(); action.   consumeStatementCase();            break;
            }
 
            //
            // Rule 86:  labeled_statement ::= default : unmatched_statement
            //
            case 86: { action.beforeConsume(); action.   consumeStatementDefault();            break;
            }
 
            //
            // Rule 87:  labeled_statement_matched ::= label_identifier : matched_statement
            //
            case 87: { action.beforeConsume(); action.   consumeStatementLabeled();            break;
            }
 
            //
            // Rule 88:  labeled_statement_matched ::= case constant_expression : matched_statement
            //
            case 88: { action.beforeConsume(); action.   consumeStatementCase();            break;
            }
 
            //
            // Rule 89:  labeled_statement_matched ::= default : matched_statement
            //
            case 89: { action.beforeConsume(); action.   consumeStatementDefault();            break;
            }
 
            //
            // Rule 90:  label_identifier ::= identifier
            //
            case 90: { action.beforeConsume(); action.   consumeName();            break;
            }
 
            //
            // Rule 91:  compound_statement ::= { }
            //
            case 91: { action.beforeConsume(); action.   consumeStatementEmptyCompoundStatement();            break;
            }
 
            //
            // Rule 92:  compound_statement ::= <openscope> { block_item_list }
            //
            case 92: { action.beforeConsume(); action.   consumeStatementCompoundStatement();            break;
            }
 
            //
            // Rule 95:  expression_statement ::= ;
            //
            case 95: { action.beforeConsume(); action.   consumeStatementNull();            break;
            }
 
            //
            // Rule 96:  expression_statement ::= expression_in_statement ;
            //
            case 96: { action.beforeConsume(); action.   consumeStatementExpression();            break;
            }
 
            //
            // Rule 98:  block_item ::= declaration
            //
            case 98: { action.beforeConsume(); action.   consumeStatementDeclaration();            break;
            }
 
            //
            // Rule 99:  switch_statement ::= switch ( expression ) unmatched_statement
            //
            case 99: { action.beforeConsume(); action.   consumeStatementSwitch();            break;
            }
 
            //
            // Rule 100:  switch_statement_matched ::= switch ( expression ) matched_statement
            //
            case 100: { action.beforeConsume(); action.   consumeStatementSwitch();            break;
            }
 
            //
            // Rule 101:  unmatched_statement ::= if ( expression ) statement
            //
            case 101: { action.beforeConsume(); action.   consumeStatementIfThen();            break;
            }
 
            //
            // Rule 102:  unmatched_statement ::= if ( expression ) matched_statement else unmatched_statement
            //
            case 102: { action.beforeConsume(); action.   consumeStatementIfThenElse();            break;
            }
 
            //
            // Rule 106:  matched_statement ::= if ( expression ) matched_statement else matched_statement
            //
            case 106: { action.beforeConsume(); action.   consumeStatementIfThenElse();            break;
            }
 
            //
            // Rule 113:  iteration_statement ::= while ( expression ) unmatched_statement
            //
            case 113: { action.beforeConsume(); action.   consumeStatementWhileLoop();            break;
            }
 
            //
            // Rule 114:  iteration_statement ::= for ( expression ; expression ; expression ) unmatched_statement
            //
            case 114: { action.beforeConsume(); action.   consumeStatementForLoop(true, true, true);            break;
            }
 
            //
            // Rule 115:  iteration_statement ::= for ( expression ; expression ; ) unmatched_statement
            //
            case 115: { action.beforeConsume(); action.   consumeStatementForLoop(true, true, false);            break;
            }
 
            //
            // Rule 116:  iteration_statement ::= for ( expression ; ; expression ) unmatched_statement
            //
            case 116: { action.beforeConsume(); action.   consumeStatementForLoop(true, false, true);            break;
            }
 
            //
            // Rule 117:  iteration_statement ::= for ( expression ; ; ) unmatched_statement
            //
            case 117: { action.beforeConsume(); action.   consumeStatementForLoop(true, false, false);            break;
            }
 
            //
            // Rule 118:  iteration_statement ::= for ( ; expression ; expression ) unmatched_statement
            //
            case 118: { action.beforeConsume(); action.   consumeStatementForLoop(false, true, true);            break;
            }
 
            //
            // Rule 119:  iteration_statement ::= for ( ; expression ; ) unmatched_statement
            //
            case 119: { action.beforeConsume(); action.   consumeStatementForLoop(false, true, false);            break;
            }
 
            //
            // Rule 120:  iteration_statement ::= for ( ; ; expression ) unmatched_statement
            //
            case 120: { action.beforeConsume(); action.   consumeStatementForLoop(false, false, true);            break;
            }
 
            //
            // Rule 121:  iteration_statement ::= for ( ; ; ) unmatched_statement
            //
            case 121: { action.beforeConsume(); action.   consumeStatementForLoop(false, false, false);            break;
            }
 
            //
            // Rule 122:  iteration_statement ::= for ( declaration expression ; expression ) unmatched_statement
            //
            case 122: { action.beforeConsume(); action.   consumeStatementForLoop(true, true, true);            break;
            }
 
            //
            // Rule 123:  iteration_statement ::= for ( declaration expression ; ) unmatched_statement
            //
            case 123: { action.beforeConsume(); action.   consumeStatementForLoop(true, true, false);            break;
            }
 
            //
            // Rule 124:  iteration_statement ::= for ( declaration ; expression ) unmatched_statement
            //
            case 124: { action.beforeConsume(); action.   consumeStatementForLoop(true, false, true);            break;
            }
 
            //
            // Rule 125:  iteration_statement ::= for ( declaration ; ) unmatched_statement
            //
            case 125: { action.beforeConsume(); action.   consumeStatementForLoop(true, false, false);            break;
            }
 
            //
            // Rule 126:  iteration_statement_matched ::= do statement while ( expression ) ;
            //
            case 126: { action.beforeConsume(); action.   consumeStatementDoLoop();            break;
            }
 
            //
            // Rule 127:  iteration_statement_matched ::= while ( expression ) matched_statement
            //
            case 127: { action.beforeConsume(); action.   consumeStatementWhileLoop();            break;
            }
 
            //
            // Rule 128:  iteration_statement_matched ::= for ( expression ; expression ; expression ) matched_statement
            //
            case 128: { action.beforeConsume(); action.   consumeStatementForLoop(true, true, true);            break;
            }
 
            //
            // Rule 129:  iteration_statement_matched ::= for ( expression ; expression ; ) matched_statement
            //
            case 129: { action.beforeConsume(); action.   consumeStatementForLoop(true, true, false);            break;
            }
 
            //
            // Rule 130:  iteration_statement_matched ::= for ( expression ; ; expression ) matched_statement
            //
            case 130: { action.beforeConsume(); action.   consumeStatementForLoop(true, false, true);            break;
            }
 
            //
            // Rule 131:  iteration_statement_matched ::= for ( expression ; ; ) matched_statement
            //
            case 131: { action.beforeConsume(); action.   consumeStatementForLoop(true, false, false);            break;
            }
 
            //
            // Rule 132:  iteration_statement_matched ::= for ( ; expression ; expression ) matched_statement
            //
            case 132: { action.beforeConsume(); action.   consumeStatementForLoop(false, true, true);            break;
            }
 
            //
            // Rule 133:  iteration_statement_matched ::= for ( ; expression ; ) matched_statement
            //
            case 133: { action.beforeConsume(); action.   consumeStatementForLoop(false, true, false);            break;
            }
 
            //
            // Rule 134:  iteration_statement_matched ::= for ( ; ; expression ) matched_statement
            //
            case 134: { action.beforeConsume(); action.   consumeStatementForLoop(false, false, true);            break;
            }
 
            //
            // Rule 135:  iteration_statement_matched ::= for ( ; ; ) matched_statement
            //
            case 135: { action.beforeConsume(); action.   consumeStatementForLoop(false, false, false);            break;
            }
 
            //
            // Rule 136:  iteration_statement_matched ::= for ( declaration expression ; expression ) matched_statement
            //
            case 136: { action.beforeConsume(); action.   consumeStatementForLoop(true, true, true);            break;
            }
 
            //
            // Rule 137:  iteration_statement_matched ::= for ( declaration expression ; ) matched_statement
            //
            case 137: { action.beforeConsume(); action.   consumeStatementForLoop(true, true, false);            break;
            }
 
            //
            // Rule 138:  iteration_statement_matched ::= for ( declaration ; expression ) matched_statement
            //
            case 138: { action.beforeConsume(); action.   consumeStatementForLoop(true, false, true);            break;
            }
 
            //
            // Rule 139:  iteration_statement_matched ::= for ( declaration ; ) matched_statement
            //
            case 139: { action.beforeConsume(); action.   consumeStatementForLoop(true, false, false);            break;
            }
 
            //
            // Rule 140:  jump_statement ::= goto identifier ;
            //
            case 140: { action.beforeConsume(); action.   consumeStatementGoto();            break;
            }
 
            //
            // Rule 141:  jump_statement ::= continue ;
            //
            case 141: { action.beforeConsume(); action.   consumeStatementContinue();            break;
            }
 
            //
            // Rule 142:  jump_statement ::= break ;
            //
            case 142: { action.beforeConsume(); action.   consumeStatementBreak();            break;
            }
 
            //
            // Rule 143:  jump_statement ::= return ;
            //
            case 143: { action.beforeConsume(); action.   consumeStatementReturn(false);            break;
            }
 
            //
            // Rule 144:  jump_statement ::= return expression ;
            //
            case 144: { action.beforeConsume(); action.   consumeStatementReturn(true);            break;
            }
 
            //
            // Rule 145:  declaration ::= declaration_specifiers ;
            //
            case 145: { action.beforeConsume(); action.   consumeDeclaration(false);            break;
            }
 
            //
            // Rule 146:  declaration ::= declaration_specifiers <openscope> init_declarator_list ;
            //
            case 146: { action.beforeConsume(); action.   consumeDeclaration(true);            break;
            }
 
            //
            // Rule 147:  declaration_specifiers ::= <openscope> simple_declaration_specifiers
            //
            case 147: { action.beforeConsume(); action.   consumeDeclarationSpecifiersSimple();           break;
            }
 
            //
            // Rule 148:  declaration_specifiers ::= <openscope> struct_or_union_declaration_specifiers
            //
            case 148: { action.beforeConsume(); action.   consumeDeclarationSpecifiersStructUnionEnum();           break;
            }
 
            //
            // Rule 149:  declaration_specifiers ::= <openscope> enum_declaration_specifiers
            //
            case 149: { action.beforeConsume(); action.   consumeDeclarationSpecifiersStructUnionEnum();           break;
            }
 
            //
            // Rule 150:  declaration_specifiers ::= <openscope> typdef_name_declaration_specifiers
            //
            case 150: { action.beforeConsume(); action.   consumeDeclarationSpecifiersTypedefName();           break;
            }
 
            //
            // Rule 177:  init_declarator ::= declarator = initializer
            //
            case 177: { action.beforeConsume(); action.   consumeDeclaratorWithInitializer();            break;
            }
 
            //
            // Rule 178:  storage_class_specifier ::= typedef
            //
            case 178: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 179:  storage_class_specifier ::= extern
            //
            case 179: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 180:  storage_class_specifier ::= static
            //
            case 180: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 181:  storage_class_specifier ::= auto
            //
            case 181: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 182:  storage_class_specifier ::= register
            //
            case 182: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 183:  type_specifier ::= void
            //
            case 183: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 184:  type_specifier ::= char
            //
            case 184: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 185:  type_specifier ::= short
            //
            case 185: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 186:  type_specifier ::= int
            //
            case 186: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 187:  type_specifier ::= long
            //
            case 187: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 188:  type_specifier ::= float
            //
            case 188: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 189:  type_specifier ::= double
            //
            case 189: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 190:  type_specifier ::= signed
            //
            case 190: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 191:  type_specifier ::= unsigned
            //
            case 191: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 192:  type_specifier ::= _Bool
            //
            case 192: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 193:  type_specifier ::= _Complex
            //
            case 193: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 194:  type_specifier ::= _Imaginary
            //
            case 194: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 195:  typedef_name ::= identifier
            //
            case 195: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 196:  struct_or_union_specifier ::= struct { <openscope> struct_declaration_list_opt }
            //
            case 196: { action.beforeConsume(); action.   consumeTypeSpecifierComposite(false, IASTCompositeTypeSpecifier.k_struct);            break;
            }
 
            //
            // Rule 197:  struct_or_union_specifier ::= union { <openscope> struct_declaration_list_opt }
            //
            case 197: { action.beforeConsume(); action.   consumeTypeSpecifierComposite(false, IASTCompositeTypeSpecifier.k_union);            break;
            }
 
            //
            // Rule 198:  struct_or_union_specifier ::= struct struct_or_union_identifier { <openscope> struct_declaration_list_opt }
            //
            case 198: { action.beforeConsume(); action.   consumeTypeSpecifierComposite(true, IASTCompositeTypeSpecifier.k_struct);            break;
            }
 
            //
            // Rule 199:  struct_or_union_specifier ::= union struct_or_union_identifier { <openscope> struct_declaration_list_opt }
            //
            case 199: { action.beforeConsume(); action.   consumeTypeSpecifierComposite(true, IASTCompositeTypeSpecifier.k_union);            break;
            }
 
            //
            // Rule 200:  struct_or_union_specifier ::= struct struct_or_union_identifier
            //
            case 200: { action.beforeConsume(); action.   consumeTypeSpecifierElaborated(IASTElaboratedTypeSpecifier.k_struct);            break;
            }
 
            //
            // Rule 201:  struct_or_union_specifier ::= union struct_or_union_identifier
            //
            case 201: { action.beforeConsume(); action.   consumeTypeSpecifierElaborated(IASTElaboratedTypeSpecifier.k_union);            break;
            }
 
            //
            // Rule 202:  struct_or_union_identifier ::= identifier
            //
            case 202: { action.beforeConsume(); action.   consumeName();            break;
            }
 
            //
            // Rule 207:  struct_declaration ::= specifier_qualifier_list <openscope> struct_declarator_list ;
            //
            case 207: { action.beforeConsume(); action.   consumeStructDeclaration(true);            break;
            }
 
            //
            // Rule 208:  struct_declaration ::= specifier_qualifier_list ;
            //
            case 208: { action.beforeConsume(); action.   consumeStructDeclaration(false);            break;
            }
 
            //
            // Rule 213:  struct_declarator ::= : constant_expression
            //
            case 213: { action.beforeConsume(); action.   consumeStructBitField(false);            break;
            }
 
            //
            // Rule 214:  struct_declarator ::= declarator : constant_expression
            //
            case 214: { action.beforeConsume(); action.   consumeStructBitField(true);             break;
            }
 
            //
            // Rule 215:  enum_identifier ::= identifier
            //
            case 215: { action.beforeConsume(); action.   consumeName();            break;
            }
 
            //
            // Rule 216:  enum_specifier ::= enum { <openscope> enumerator_list_opt }
            //
            case 216: { action.beforeConsume(); action.   consumeTypeSpecifierEnumeration(false);            break;
            }
 
            //
            // Rule 217:  enum_specifier ::= enum enum_identifier { <openscope> enumerator_list_opt }
            //
            case 217: { action.beforeConsume(); action.   consumeTypeSpecifierEnumeration(true);            break;
            }
 
            //
            // Rule 218:  enum_specifier ::= enum { <openscope> enumerator_list_opt , }
            //
            case 218: { action.beforeConsume(); action.   consumeTypeSpecifierEnumeration(false);            break;
            }
 
            //
            // Rule 219:  enum_specifier ::= enum enum_identifier { <openscope> enumerator_list_opt , }
            //
            case 219: { action.beforeConsume(); action.   consumeTypeSpecifierEnumeration(true);            break;
            }
 
            //
            // Rule 220:  enum_specifier ::= enum enum_identifier
            //
            case 220: { action.beforeConsume(); action.   consumeTypeSpecifierElaborated(IASTElaboratedTypeSpecifier.k_enum);            break;
            }
 
            //
            // Rule 225:  enumerator ::= enum_identifier
            //
            case 225: { action.beforeConsume(); action.   consumeEnumerator(false);            break;
            }
 
            //
            // Rule 226:  enumerator ::= enum_identifier = constant_expression
            //
            case 226: { action.beforeConsume(); action.   consumeEnumerator(true);            break;
            }
 
            //
            // Rule 227:  type_qualifier ::= const
            //
            case 227: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 228:  type_qualifier ::= restrict
            //
            case 228: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 229:  type_qualifier ::= volatile
            //
            case 229: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 230:  function_specifier ::= inline
            //
            case 230: { action.beforeConsume(); action.   consumeToken();            break;
            }
 
            //
            // Rule 232:  declarator ::= <openscope> pointer direct_declarator
            //
            case 232: { action.beforeConsume(); action.   consumeDeclaratorWithPointer(true);            break;
            }
 
            //
            // Rule 233:  direct_declarator ::= identifier
            //
            case 233: { action.beforeConsume(); action.   consumeDirectDeclaratorIdentifier();            break;
            }
 
            //
            // Rule 234:  direct_declarator ::= ( declarator )
            //
            case 234: { action.beforeConsume(); action.   consumeDirectDeclaratorBracketed();            break;
            }
 
            //
            // Rule 235:  direct_declarator ::= direct_declarator ( <openscope> parameter_type_list )
            //
            case 235: { action.beforeConsume(); action.   consumeDirectDeclaratorFunctionDeclarator(true);            break;
            }
 
            //
            // Rule 236:  direct_declarator ::= direct_declarator ( )
            //
            case 236: { action.beforeConsume(); action.   consumeDirectDeclaratorFunctionDeclarator(false);            break;
            }
 
            //
            // Rule 237:  direct_declarator ::= direct_declarator array_modifier
            //
            case 237: { action.beforeConsume(); action.   consumeDirectDeclaratorArrayDeclarator();            break;
            }
 
            //
            // Rule 238:  knr_direct_declarator ::= direct_declarator ( <openscope> identifier_list )
            //
            case 238: { action.beforeConsume(); action.   consumeDirectDeclaratorFunctionDeclaratorKnR();            break;
            }
 
            //
            // Rule 240:  knr_function_declarator ::= <openscope> pointer knr_direct_declarator
            //
            case 240: { action.beforeConsume(); action.   consumeDeclaratorWithPointer(true);            break;
            }
 
            //
            // Rule 241:  array_modifier ::= [ ]
            //
            case 241: { action.beforeConsume(); action.   consumeDirectDeclaratorArrayModifier(false);            break;
            }
 
            //
            // Rule 242:  array_modifier ::= [ <openscope> type_qualifier_list ]
            //
            case 242: { action.beforeConsume(); action.   consumeDirectDeclaratorModifiedArrayModifier(false, false, true,  false);            break;
            }
 
            //
            // Rule 243:  array_modifier ::= [ assignment_expression ]
            //
            case 243: { action.beforeConsume(); action.   consumeDirectDeclaratorArrayModifier(true );            break;
            }
 
            //
            // Rule 244:  array_modifier ::= [ <openscope> type_qualifier_list assignment_expression ]
            //
            case 244: { action.beforeConsume(); action.   consumeDirectDeclaratorModifiedArrayModifier(false, false, true,  true );            break;
            }
 
            //
            // Rule 245:  array_modifier ::= [ static assignment_expression ]
            //
            case 245: { action.beforeConsume(); action.   consumeDirectDeclaratorModifiedArrayModifier(true,  false, false, true );            break;
            }
 
            //
            // Rule 246:  array_modifier ::= [ static <openscope> type_qualifier_list assignment_expression ]
            //
            case 246: { action.beforeConsume(); action.   consumeDirectDeclaratorModifiedArrayModifier(true,  false, true,  true );            break;
            }
 
            //
            // Rule 247:  array_modifier ::= [ <openscope> type_qualifier_list static assignment_expression ]
            //
            case 247: { action.beforeConsume(); action.   consumeDirectDeclaratorModifiedArrayModifier(true,  false, true,  true );            break;
            }
 
            //
            // Rule 248:  array_modifier ::= [ * ]
            //
            case 248: { action.beforeConsume(); action.   consumeDirectDeclaratorModifiedArrayModifier(false, true,  false, false);            break;
            }
 
            //
            // Rule 249:  array_modifier ::= [ <openscope> type_qualifier_list * ]
            //
            case 249: { action.beforeConsume(); action.   consumeDirectDeclaratorModifiedArrayModifier(false, true,  true,  false);            break;
            }
 
            //
            // Rule 250:  pointer ::= *
            //
            case 250: { action.beforeConsume(); action.   consumePointer();            break;
            }
 
            //
            // Rule 251:  pointer ::= pointer *
            //
            case 251: { action.beforeConsume(); action.   consumePointer();            break;
            }
 
            //
            // Rule 252:  pointer ::= * <openscope> type_qualifier_list
            //
            case 252: { action.beforeConsume(); action.   consumePointerTypeQualifierList();            break;
            }
 
            //
            // Rule 253:  pointer ::= pointer * <openscope> type_qualifier_list
            //
            case 253: { action.beforeConsume(); action.   consumePointerTypeQualifierList();            break;
            }
 
            //
            // Rule 261:  parameter_declaration ::= declaration_specifiers init_declarator
            //
            case 261: { action.beforeConsume(); action.   consumeParameterDeclaration(true);            break;
            }
 
            //
            // Rule 262:  parameter_declaration ::= declaration_specifiers
            //
            case 262: { action.beforeConsume(); action.   consumeParameterDeclaration(false);           break;
            }
 
            //
            // Rule 263:  parameter_declaration ::= declaration_specifiers abstract_declarator
            //
            case 263: { action.beforeConsume(); action.   consumeParameterDeclaration(true);            break;
            }
 
            //
            // Rule 264:  identifier_list ::= identifier
            //
            case 264: { action.beforeConsume(); action.   consumeName();            break;
            }
 
            //
            // Rule 265:  identifier_list ::= identifier_list , identifier
            //
            case 265: { action.beforeConsume(); action.   consumeName();            break;
            }
 
            //
            // Rule 266:  type_name ::= specifier_qualifier_list
            //
            case 266: { action.beforeConsume(); action.   consumeTypeId(false);            break;
            }
 
            //
            // Rule 267:  type_name ::= specifier_qualifier_list abstract_declarator
            //
            case 267: { action.beforeConsume(); action.   consumeTypeId(true);            break;
            }
 
            //
            // Rule 268:  abstract_declarator ::= <openscope> pointer
            //
            case 268: { action.beforeConsume(); action.   consumeDeclaratorWithPointer(false);            break;
            }
 
            //
            // Rule 270:  abstract_declarator ::= <openscope> pointer direct_abstract_declarator
            //
            case 270: { action.beforeConsume(); action.   consumeDeclaratorWithPointer(true);             break;
            }
 
            //
            // Rule 271:  direct_abstract_declarator ::= ( abstract_declarator )
            //
            case 271: { action.beforeConsume(); action.   consumeDirectDeclaratorBracketed();            break;
            }
 
            //
            // Rule 272:  direct_abstract_declarator ::= array_modifier
            //
            case 272: { action.beforeConsume(); action.   consumeAbstractDeclaratorArrayModifier(false);            break;
            }
 
            //
            // Rule 273:  direct_abstract_declarator ::= direct_abstract_declarator array_modifier
            //
            case 273: { action.beforeConsume(); action.   consumeAbstractDeclaratorArrayModifier(true);             break;
            }
 
            //
            // Rule 274:  direct_abstract_declarator ::= ( )
            //
            case 274: { action.beforeConsume(); action.   consumeAbstractDeclaratorFunctionDeclarator(false, false);           break;
            }
 
            //
            // Rule 275:  direct_abstract_declarator ::= direct_abstract_declarator ( )
            //
            case 275: { action.beforeConsume(); action.   consumeAbstractDeclaratorFunctionDeclarator(true, false);            break;
            }
 
            //
            // Rule 276:  direct_abstract_declarator ::= ( <openscope> parameter_type_list )
            //
            case 276: { action.beforeConsume(); action.   consumeAbstractDeclaratorFunctionDeclarator(false, true);            break;
            }
 
            //
            // Rule 277:  direct_abstract_declarator ::= direct_abstract_declarator ( <openscope> parameter_type_list )
            //
            case 277: { action.beforeConsume(); action.   consumeAbstractDeclaratorFunctionDeclarator(true, true);             break;
            }
 
            //
            // Rule 278:  initializer ::= assignment_expression
            //
            case 278: { action.beforeConsume(); action.   consumeInitializer();            break;
            }
 
            //
            // Rule 279:  initializer ::= { <openscope> initializer_list }
            //
            case 279: { action.beforeConsume(); action.   consumeInitializerList();            break;
            }
 
            //
            // Rule 280:  initializer ::= { <openscope> initializer_list , }
            //
            case 280: { action.beforeConsume(); action.   consumeInitializerList();            break;
            }
 
            //
            // Rule 285:  designated_initializer ::= <openscope> designation initializer
            //
            case 285: { action.beforeConsume(); action.   consumeInitializerDesignated();            break;
            }
 
            //
            // Rule 289:  designator ::= [ constant_expression ]
            //
            case 289: { action.beforeConsume(); action.   consumeDesignatorArrayDesignator();            break;
            }
 
            //
            // Rule 290:  designator ::= . identifier
            //
            case 290: { action.beforeConsume(); action.   consumeDesignatorFieldDesignator();            break;
            }
 
            //
            // Rule 291:  translation_unit ::= external_declaration_list
            //
            case 291: { action.beforeConsume(); action.   consumeTranslationUnit();            break;
            }
 
            //
            // Rule 292:  translation_unit ::= $Empty
            //
            case 292: { action.beforeConsume(); action.   consumeTranslationUnit();            break;
            }
 
            //
            // Rule 297:  external_declaration ::= ;
            //
            case 297: { action.beforeConsume(); action.   consumeDeclarationEmpty();           break;
            }
 
            //
            // Rule 298:  external_declaration ::= ERROR_TOKEN
            //
            case 298: { action.beforeConsume(); action.   consumeDeclarationProblem();            break;
            }
 
            //
            // Rule 299:  function_definition ::= declaration_specifiers <openscope> declarator compound_statement
            //
            case 299: { action.beforeConsume(); action.   consumeFunctionDefinition();            break;
            }
 
            //
            // Rule 300:  function_definition ::= declaration_specifiers <openscope> knr_function_declarator <openscope> declaration_list compound_statement
            //
            case 300: { action.beforeConsume(); action.   consumeFunctionDefinitionKnR();            break;
            }

    
            default:
                break;
        }
        return;
    }
}

